export const FETCH_CRYPTO_DATA_REQUEST = 'FETCH_CRYPTO_DATA_REQUEST';
export const FETCH_CRYPTO_DATA_SUCCESS = 'FETCH_CRYPTO_DATA_SUCCESS';
export const FETCH_CRYPTO_DATA_FAILURE = 'FETCH_CRYPTO_DATA_FAILURE';
export const SORT_DATA_TABLE = 'SORT_DATA_TABLE';
