export const FETCH_CRYPTO_DATA_REQUEST = 'FETCH_CRYPTO_DATA_REQUEST';
export const FETCH_CRYPTO_DATA_SUCCESS = 'FETCH_CRYPTO_DATA_SUCCESS';
export const FETCH_CRYPTO_DATA_FAILURE = 'FETCH_CRYPTO_DATA_FAILURE';

export const FETCH_CRYPTO_BY_ID_INIT = 'FETCH_CRYPTO_BY_ID_INIT';
export const FETCH_CRYPTO_DATA_BY_ID_REQUEST = 'FETCH_CRYPTO_DATA_BY_ID_REQUEST';
export const FETCH_CRYPTO_DATA_BY_ID_SUCCESS = 'FETCH_CRYPTO_DATA_BY_ID_SUCCESS';
export const FETCH_CRYPTO_DATA_BY_ID_FAILURE = 'FETCH_CRYPTO_DATA_BY_ID_FAILURE';

export const SORT_DATA_TABLE = 'SORT_DATA_TABLE';
